<a href="https://colab.research.google.com/github/anamika-aryal/pyhton-basics-colab/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy- numerical python
benefits/importance:
1. allows mathmatical operation
2. faster operation

In [ ]:
import numpy as np #numpy->python library-> has tons of function.

List vs numpy

In [ ]:
from time import process_time

time taken by list


In [ ]:
python_list=[i for i in range (10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.000741215999999767


In [ ]:
np_array=np.array([i for i in range(10000)])

start_time=process_time()

np_array += 5

end_time=process_time()

print(end_time-start_time)

0.00019263200000096958


Numpy Arrays

In [ ]:
#numpy arrays:
np_array=np.array([1,2,3,4])
print(np_array)
type(np_array) #ndarray--> nth dimensional array,similiar to matrix

[1 2 3 4]


numpy.ndarray

In [ ]:
# 1D array:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
#2D array:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape #--> shape= (rows, columns)

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [ ]:
#float type numpy
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float) #--> changes to floating point numpy array, default is int.
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial placeholers in numpy array:


ℹ initialize (like int a; in c)


In [2]:
# create a numpy array of zeros
import numpy as np
x = np.zeros((4,5)) #zeros() creates a array of 0's where there is 4 rows and 5 column.
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
# numpy array of 1's
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
# array of particular value:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [7]:
# identity matrix
i = np.eye(5, dtype=int)
print(i)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [9]:
# create a numpy array with random values:
r = np.random.random((3,4))
print(r)

[[0.68365458 0.66278562 0.43984189 0.80608806]
 [0.41345575 0.81925206 0.9585483  0.57145712]
 [0.70071252 0.91418785 0.55700525 0.51826539]]


In [11]:
# random integer values array within a range.
r2=np.random.randint(10,50, (3,5))
print(r2)

[[43 19 24 19 34]
 [16 34 32 10 48]
 [10 21 38 23 38]]


In [14]:
# array of evenly spaced values: specifying the number of values required.
e = np.linspace(10,30,8, dtype=int)
print(e)

[10 12 15 18 21 24 27 30]


In [15]:
# array of evenly spaced values with step
e2 = np.arange(10,30,6)
print(e2)

[10 16 22 28]


In [16]:
# convert the list to numpy array
list2=[10,20,30,40,50]

np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 30 40 50]


numpy.ndarray

Analyze a numpy array.

Getting infomation from array, inspecting it, and trying to interpret it.

In [23]:
c = np.random.randint(10,90,(5,5))
print(c)

[[81 86 59 53 38]
 [51 22 89 88 63]
 [76 21 86 66 68]
 [86 67 37 42 75]
 [73 61 52 41 24]]


In [24]:
# find array dimension
print(c.shape)

(5, 5)


In [25]:
# no of dimension
print(c.ndim)

2


In [26]:
# no of elements in an array
print(c.size)

25


In [27]:
# checking a data type of values in the array
print(c.dtype)

int64


Mathmatical operation on numpy array:

In [29]:
a = np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[2 9 1]
 [3 3 4]
 [1 4 7]]
[[15 11 14]
 [12 16 15]
 [10 16 10]]


In [30]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[17 20 15]
 [15 19 19]
 [11 20 17]]
[[-13  -2 -13]
 [ -9 -13 -11]
 [ -9 -12  -3]]
[[30 99 14]
 [36 48 60]
 [10 64 70]]
[[0.13333333 0.81818182 0.07142857]
 [0.25       0.1875     0.26666667]
 [0.1        0.25       0.7       ]]


In [31]:
a = np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[3 1 2]
 [2 7 3]
 [6 2 5]]
[[12 19 10]
 [17 17 11]
 [15 10 10]]


In [32]:
print(np.add(a,b))
print(np.subtract(b,a))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 20 12]
 [19 24 14]
 [21 12 15]]
[[ 9 18  8]
 [15 10  8]
 [ 9  8  5]]
[[ 36  19  20]
 [ 34 119  33]
 [ 90  20  50]]
[[0.25       0.05263158 0.2       ]
 [0.11764706 0.41176471 0.27272727]
 [0.4        0.2        0.5       ]]


Array manipulation

In [35]:
# array manipulation.
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 2 1]
 [1 2 6]]
(2, 3)


In [36]:
#transpose:
trans= np.transpose(array)
print(trans)
print(trans.shape)

[[7 1]
 [2 2]
 [1 6]]
(3, 2)


In [37]:
trans2= array.T
print(trans2)
print(trans2.shape)

[[7 1]
 [2 2]
 [1 6]]
(3, 2)


In [38]:
# reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 4 9]
 [2 1 9]]
(2, 3)


In [39]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[5 4]
 [9 2]
 [1 9]]
(3, 2)
